Repository deep5050/cppcheck-action, pull requests merged in 2021-04, with the labels that each got.

#36 Added Support for --std=arg and --force options
  README.md
  src/entrypoint.py
Labels: size/M

#40 Fix action warning and enhanced readme styling
  README.md
  action.yml
Labels: size/S

#23 Experimental support for user extensible cppcheck options
  action.yml
  src/entrypoint.py
Labels: size/M

#46 Complete PR#23
  LICENSE
  README.md
Labels: size/XS
